#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pylibmc
Version  : 1.5.2
Release  : 28
URL      : http://pypi.debian.net/pylibmc/pylibmc-1.5.2.tar.gz
Source0  : http://pypi.debian.net/pylibmc/pylibmc-1.5.2.tar.gz
Summary  : Quick and small memcached client for Python
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pylibmc-python
BuildRequires : libmemcached-dev
BuildRequires : memcached
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : zlib-dev

%description
`pylibmc` is a Python client for `memcached <http://memcached.org/>`_ written in C.

%package python
Summary: python components for the pylibmc package.
Group: Default

%description python
python components for the pylibmc package.


%prep
%setup -q -n pylibmc-1.5.2

%build
export LANG=C
export SOURCE_DATE_EPOCH=1488827281
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1488827281
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
